# Generated by Django 4.1.3 on 2022-12-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_avno_user_account_is_avno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradmin',
            options={'verbose_name': 'User Admin', 'verbose_name_plural': 'User Admin'},
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='avno_user',
            field=models.CharField(default='', max_length=150),
        ),
    ]
