# Generated by Django 4.1.5 on 2023-01-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useradmin_options_alter_useradmin_avno_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradmin',
            options={'verbose_name': 'User Admin', 'verbose_name_plural': 'Users Admin'},
        ),
    ]
