# Generated by Django 4.1.5 on 2023-02-10 13:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacUser',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mac_user', models.CharField(default='00:00:00:00:00:00', max_length=100)),
            ],
            options={
                'verbose_name': 'MAC User',
                'verbose_name_plural': 'MAC Users',
            },
            bases=('users.account',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
