# Generated by Django 4.1.3 on 2022-11-30 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='media',
            name='campaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='media',
            field=models.ManyToManyField(to='home.media'),
        ),
        migrations.AddField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('PHOTO', 'Photo')], default='VIDEO', max_length=25),
        ),
        migrations.AlterField(
            model_name='venue',
            name='playlist',
            field=models.IntegerField(blank=True, default=0, help_text='This field is auto-filled with the number of related Campaigns', null=True),
        ),
        migrations.AlterField(
            model_name='washroom',
            name='gender',
            field=models.CharField(choices=[('FAMILY', 'Family'), ('FEMALE', 'Female'), ('MALE', 'Male')], default='FAMILY', max_length=25),
        ),
    ]
