# Generated by Django 4.1.3 on 2022-12-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='owner',
        ),
    ]
