# Generated by Django 4.1.3 on 2022-12-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_media_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='size',
        ),
    ]
