# Generated by Django 4.1.3 on 2022-12-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_media_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washroom',
            name='faucets',
        ),
        migrations.AddField(
            model_name='washroom',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washrooms', to='home.venue'),
        ),
        migrations.CreateModel(
            name='WashroomGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washrooms', models.ManyToManyField(related_name='washroom_groups', to='home.washroom')),
            ],
        ),
    ]
