# Generated by Django 4.1.3 on 2022-12-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_washroom_faucets_washroom_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='washroom_groups',
        ),
        migrations.AddField(
            model_name='faucet',
            name='washroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faucets', to='home.washroom'),
        ),
    ]
