# Generated by Django 4.1.3 on 2022-12-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_campaign_washroom_groups_faucet_washroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='washroom_groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='home.washroomgroups'),
        ),
    ]
