# Generated by Django 4.1.5 on 2023-01-26 18:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_faucet_ip_address_alter_faucet_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='washroomgroups',
            options={'verbose_name': 'Washroom Group', 'verbose_name_plural': 'Washroom Groups'},
        ),
        migrations.RemoveField(
            model_name='washroom',
            name='group_association',
        ),
        migrations.RemoveField(
            model_name='washroomgroups',
            name='washrooms',
        ),
        migrations.AddField(
            model_name='washroom',
            name='washroom_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washrooms', to='home.washroomgroups'),
        ),
        migrations.AddField(
            model_name='washroomgroups',
            name='name',
            field=models.CharField(default='Washroom Group v1', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='washroom_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='home.washroomgroups'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
