# Generated by Django 4.1.5 on 2023-01-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_washroomgroups_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='washroom',
            old_name='venue',
            new_name='venues',
        ),
        migrations.RenameField(
            model_name='washroom',
            old_name='washroom_group',
            new_name='washroom_groups',
        ),
    ]
