# Generated by Django 4.1.5 on 2023-02-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_faucet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faucet',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
