# Generated by Django 4.1.5 on 2023-02-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_macuser'),
        ('home', '0014_faucet_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faucet',
            name='token',
        ),
        migrations.AddField(
            model_name='faucet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.macuser'),
        ),
    ]
