# Generated by Django 4.1.3 on 2022-11-12 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='venues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.venue'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='washroom_groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.washroom'),
        ),
    ]
